[project]
name = "pyeveproject"
version = "0.1.0"
description = "Pet Project"
readme = "README.md"
authors = [{ name = "Moises Gallego" }]
requires-python = ">=3.14"
dependencies = ["fastapi[standard]>=0.141.1", "httpx2>=2.12.0"]

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-httpx2>=1.0.0",
    "ruff>=0.16.3",
]

[tool.ruff]
extend-exclude = [".specify"]

[tool.mypy]
strict = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.fastapi]
entrypoint = "pyeveproject.main:app"
